# Generated by Django 3.1.3 on 2021-08-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210831_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choise_content',
            new_name='choice_content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_centent',
            new_name='question_content',
        ),
    ]
